= System Services

The tabletop robot sets up two system services using `systemctl`, the first to run the ROS configuration
at startup, the second to monitor a switch to enable a graceful shutdown without having to log in
and run the shutdown command.

== Automatically Run ROS at Startup

=== /home/ubuntu/bin/tabletop

....
#! /bin/bash

# ROS setup
source /opt/ros/kinetic/setup.bash
source /home/ubuntu/catkin_ws/devel/setup.bash

ROS_MASTER_URI=http://madrid.local:11311
export ROS_HOSTNAME=madrid.local

NOW=`date +%Y-%m-%dT%H%M%S`
LOG_DIR=/home/ubuntu/log
mkdir -p $LOG_DIR
LOG_FILE=$LOG_DIR/$NOW.log

roslaunch tabletop tabletop.launch 2>&1 >$LOG_FILE
....

=== /lib/systemd/system/tabletop.service

----
[unit]
Description=Tabletop robot
Wants=network-online.target
After=network.target

[Service]
ExecStart=/home/ubuntu/bin/tabletop
ExecStop=killall -HUP roslaunch
User=ubuntu

[Install]
WantedBy=multi-user.target
----

=== Setup

To start the service: `sudo systemctl start tabletop`
To stop the service: `sudo systemctl stop tabletop`

Once satisfied it is working, enable on boot via: `sudo systemctl enable tabletop`

== Monitor Switch to Gracefully Shut Down

=== /lib/systemd/system/shutdownswitch.service

----
[unit]
Description=Shutdown switch monitor
Wants=network-online.target
After=network.target

[Service]
ExecStart=/home/ubuntu/bin/shutdownSwitch.py

[Install]
WantedBy=multi-user.target
----

=== /home/ubuntu/bin/shutdownSwitch.py

----
#! /usr/bin/env python
#This script was authored by AndrewH7 and belongs to him (www.instructables.com/member/AndrewH7)
#You have permission to modify and use this script only for your own personal usage
#You do not have permission to redistribute this script as your own work
#Use this script at your own risk

import RPi.GPIO as GPIO
import os

gpio_pin_number=40

GPIO.setmode(GPIO.BOARD)

GPIO.setup(gpio_pin_number, GPIO.IN, pull_up_down=GPIO.PUD_UP)
#It's very important the pin is an input to avoid short-circuits
#The pull-up resistor means the pin is high by default

try:
    GPIO.wait_for_edge(gpio_pin_number, GPIO.FALLING)
    #Use falling edge detection to see if pin is pulled 
    #low to avoid repeated polling
    os.system("sudo shutdown -h now")
    #Send command to system to shutdown
except:
    pass

GPIO.cleanup()
#Revert all GPIO pins to their normal states (i.e. input = safe)
----

=== Installation

See above instructions for the use of 'systemctl` to install the service.
