#! /usr/bin/env python

from __future__ import print_function
import sys
import threading
from math import cos, tan, atan2, pi
import cv2
import numpy as np
import rospy
from rospy.numpy_msg import numpy_msg
from sensor_msgs.msg import CompressedImage, LaserScan

class Position:
    def __init__(self):
        self.angle = None
        self.x = None
        self.min_y = None
        self.slope = None

class EdgeDistanceFinder:

    def __init__(self):
        self.thread_lock = threading.Lock()

    def run(self):
        rospy.init_node('calibrate_distance')
        self.frame_id = rospy.get_param('~frame_id', 'camera_link')
        self.vert_fov = rospy.get_param('~vert_fov', 43.65)*pi/180
        self.horz_fov = rospy.get_param('~horz_fov', 55.36)*pi/180
        self.min_angle = rospy.get_param('~min_angle', -24)
        self.max_angle = rospy.get_param('~max_angle', 24)
        self.angle_delta = rospy.get_param('~angle_delta', 4)
        self.ref_dist = rospy.get_param('~ref_dist', 0.4)
        self.camera_height = rospy.get_param('~camera_height', 0.13)
        self.width = rospy.get_param('~width', 640)
        self.height = rospy.get_param('~height', 480)

        self.angles = [angle*pi/180 \
                       for angle in range(self.min_angle, self.max_angle+1,
                                          self.angle_delta)]

        self.horz_fd = self.width/2 / tan(self.horz_fov/2)
        self.vert_fd = self.height/2 / tan(self.vert_fov/2)
        self.vert_refang = atan2(self.ref_dist, self.camera_height)

        self.positions = []
        for angle in self.angles:
            pos = Position()
            pos.angle = angle
            pos.x = self.width/2 - int(round(self.horz_fd*tan(angle)))
            pos.max_y = None
            pos.distance = 10.0
            pos.slope = None
            self.positions.append(pos)

        self.scan_pub = rospy.Publisher('scan', numpy_msg(LaserScan),
                                        queue_size=1)

        rospy.Subscriber('image/compressed', numpy_msg(CompressedImage),
                         self.on_image)
        rospy.spin()

    def on_image(self, msg):
        data = np.fromstring(msg.data, np.uint8)
        frame = cv2.imdecode(data, cv2.IMREAD_COLOR)
        thread = threading.Thread(target=self.process_image,
                                  args=(msg.header, frame))
        thread.setDaemon(True)
        thread.start()

    def process_image(self, header, frame):
        # Skip this image if we're already processing an image.
        # That is, if we cannot acquire the thread lock with no
        # delay, then another thread has the lock and is processing
        # an image. This reduces our effective frame rate to what
        # we can process.
        if not self.thread_lock.acquire(False):
            rospy.loginfo('Skipping frame because other thread busy')
            return

        try:
            im_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            med = np.median(im_gray)
            lower = int(max(0, (1 - 0.5)*med))
            upper = int(min(255, (1 + 0.5)*med))
            edges = cv2.Canny(im_gray, lower, upper)
            kernel = np.ones((3,3), np.uint8)
            edges = cv2.dilate(edges, kernel, iterations=1)

            lines = cv2.HoughLinesP(edges, 1, 1*np.pi/180, 50, minLineLength=75, maxLineGap=10)

            if lines is None:
                return

            for pos in self.positions:
                pos.max_y = None
                pos.distance = 10.0
                pos.slope = None

            margin = 3
            for line in lines:
                x0, y0, x1, y1 = line[0]
                if x0 >= self.width-margin and x1 >= self.width-margin \
                   or y0 >= self.height-margin and y1 >= self.height-margin:
                    continue
            
                # Make sure line goes to the right.
                if x0 > x1:
                    x0,x1 = x1,x0
                    y0,y1 = y1,y0

                for pos in self.positions:
                    if x0 < pos.x and x1 >= pos.x:
                        slope = float(y1 - y0) / (x1 - x0)
                        y = int(round(y0 + slope*(pos.x - x0)))
                        if (pos.max_y is None) or y > pos.max_y:
                            pos.max_y = y
                            pos.slope = -slope
                            pos.distance \
                                = self.get_distance(self.width/2 - pos.x,
                                                    self.height/2 - y,
                                                    self.camera_height,
                                                    self.horz_fd,
                                                    self.vert_refang,
                                                    self.vert_fd)

            scan = LaserScan()
            scan.header.stamp = rospy.Time.now()
            scan.header.frame_id = self.frame_id
            scan.angle_min = self.min_angle*pi/180
            scan.angle_max = self.max_angle*pi/180
            scan.angle_increment = self.angle_delta*pi/180
            scan.time_increment = 0
            scan.scan_time = 0
            scan.range_min = 0
            scan.range_max = 2.0
            scan.ranges = [pos.distance for pos in self.positions]
            self.scan_pub.publish(scan)

        finally:
            self.thread_lock.release()

    def get_distance(self, dx, dy, camera_height, horz_fd, vert_refang, vert_fd):
        horz_angle = abs(atan2(dx, horz_fd))
        vert_angle = vert_refang + atan2(dy, vert_fd)
        dist_ahead = camera_height * tan(vert_angle)
        return dist_ahead / cos(horz_angle)

if __name__ == "__main__":
    try:
        EdgeDistanceFinder().run()

    except rospy.ROSInterruptException:
        pass
